name: Build site and release
on:
  pull_request:
    types:
      - closed
jobs:
  release:
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Setup Dependencies
        run: pdm sync

      - name: Build site
        run: pdm run mkdocs build

      - name: Export Slides HTML
        run: npx @marp-team/marp-cli@latest SLIDES.md -o site/PyTexasMeetup-0923-Slides.html --html true

      - name: Zip files
        run: zip -r release.zip site

      - name: Tag branch (main only)
        if: endswith(github.ref, 'main')
        uses: mydea/action-tag-date-version@v20
        id: version-tag

      - name: Cut a release (main only)
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          artifacts: release.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version-tag.outputs.version }}
